/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as DotwellKnownAgentManifestDotjsonRouteImport } from './routes/[.]well-known/agent-manifest[.]json'
import { Route as DotwellKnownAgentsDotjsonRouteImport } from './routes/[.]well-known/agents[.]json'
import { Route as DotwellKnownAiPluginDotjsonRouteImport } from './routes/[.]well-known/ai-plugin[.]json'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicV1ClaimRouteImport } from './routes/api/public/v1/claim'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1PricingRouteImport } from './routes/api/public/v1/pricing'
import { Route as ApiPublicV1SignupRouteImport } from './routes/api/public/v1/signup'
import { Route as ApiPublicV1ToolsRouteImport } from './routes/api/public/v1/tools'
import { Route as ApiPublicV1CreditsPurchaseRouteImport } from './routes/api/public/v1/credits.purchase'
import { Route as ApiPublicV1KeysRotateRouteImport } from './routes/api/public/v1/keys.rotate'
import { Route as ApiPublicV1ToolsToolNameRouteImport } from './routes/api/public/v1/tools.$toolName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentManifestDotjsonRoute =
  DotwellKnownAgentManifestDotjsonRouteImport.update({
    id: '/.well-known/agent-manifest.json',
    path: '/.well-known/agent-manifest.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentsDotjsonRoute =
  DotwellKnownAgentsDotjsonRouteImport.update({
    id: '/.well-known/agents.json',
    path: '/.well-known/agents.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAiPluginDotjsonRoute =
  DotwellKnownAiPluginDotjsonRouteImport.update({
    id: '/.well-known/ai-plugin.json',
    path: '/.well-known/ai-plugin.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClaimRoute = ApiPublicV1ClaimRouteImport.update({
  id: '/api/public/v1/claim',
  path: '/api/public/v1/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PricingRoute = ApiPublicV1PricingRouteImport.update({
  id: '/api/public/v1/pricing',
  path: '/api/public/v1/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SignupRoute = ApiPublicV1SignupRouteImport.update({
  id: '/api/public/v1/signup',
  path: '/api/public/v1/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ToolsRoute = ApiPublicV1ToolsRouteImport.update({
  id: '/api/public/v1/tools',
  path: '/api/public/v1/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CreditsPurchaseRoute =
  ApiPublicV1CreditsPurchaseRouteImport.update({
    id: '/api/public/v1/credits/purchase',
    path: '/api/public/v1/credits/purchase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1KeysRotateRoute = ApiPublicV1KeysRotateRouteImport.update({
  id: '/api/public/v1/keys/rotate',
  path: '/api/public/v1/keys/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ToolsToolNameRoute =
  ApiPublicV1ToolsToolNameRouteImport.update({
    id: '/$toolName',
    path: '/$toolName',
    getParentRoute: () => ApiPublicV1ToolsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/agent-manifest.json': typeof DotwellKnownAgentManifestDotjsonRoute
  '/.well-known/agents.json': typeof DotwellKnownAgentsDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/api/agent': typeof ApiAgentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/v1/claim': typeof ApiPublicV1ClaimRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/signup': typeof ApiPublicV1SignupRoute
  '/api/public/v1/tools': typeof ApiPublicV1ToolsRouteWithChildren
  '/api/public/v1/credits/purchase': typeof ApiPublicV1CreditsPurchaseRoute
  '/api/public/v1/keys/rotate': typeof ApiPublicV1KeysRotateRoute
  '/api/public/v1/tools/$toolName': typeof ApiPublicV1ToolsToolNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/agent-manifest.json': typeof DotwellKnownAgentManifestDotjsonRoute
  '/.well-known/agents.json': typeof DotwellKnownAgentsDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/api/agent': typeof ApiAgentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/v1/claim': typeof ApiPublicV1ClaimRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/signup': typeof ApiPublicV1SignupRoute
  '/api/public/v1/tools': typeof ApiPublicV1ToolsRouteWithChildren
  '/api/public/v1/credits/purchase': typeof ApiPublicV1CreditsPurchaseRoute
  '/api/public/v1/keys/rotate': typeof ApiPublicV1KeysRotateRoute
  '/api/public/v1/tools/$toolName': typeof ApiPublicV1ToolsToolNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/agent-manifest.json': typeof DotwellKnownAgentManifestDotjsonRoute
  '/.well-known/agents.json': typeof DotwellKnownAgentsDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/api/agent': typeof ApiAgentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/v1/claim': typeof ApiPublicV1ClaimRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/signup': typeof ApiPublicV1SignupRoute
  '/api/public/v1/tools': typeof ApiPublicV1ToolsRouteWithChildren
  '/api/public/v1/credits/purchase': typeof ApiPublicV1CreditsPurchaseRoute
  '/api/public/v1/keys/rotate': typeof ApiPublicV1KeysRotateRoute
  '/api/public/v1/tools/$toolName': typeof ApiPublicV1ToolsToolNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/claim'
    | '/connect'
    | '/docs'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/agent-manifest.json'
    | '/.well-known/agents.json'
    | '/.well-known/ai-plugin.json'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/billing'
    | '/keys'
    | '/settings'
    | '/tools'
    | '/usage'
    | '/api/agent'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/public/stripe/webhook'
    | '/api/public/v1/claim'
    | '/api/public/v1/me'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/pricing'
    | '/api/public/v1/signup'
    | '/api/public/v1/tools'
    | '/api/public/v1/credits/purchase'
    | '/api/public/v1/keys/rotate'
    | '/api/public/v1/tools/$toolName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/claim'
    | '/connect'
    | '/docs'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/agent-manifest.json'
    | '/.well-known/agents.json'
    | '/.well-known/ai-plugin.json'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/billing'
    | '/keys'
    | '/settings'
    | '/tools'
    | '/usage'
    | '/api/agent'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/chat'
    | '/api/public/stripe/webhook'
    | '/api/public/v1/claim'
    | '/api/public/v1/me'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/pricing'
    | '/api/public/v1/signup'
    | '/api/public/v1/tools'
    | '/api/public/v1/credits/purchase'
    | '/api/public/v1/keys/rotate'
    | '/api/public/v1/tools/$toolName'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/claim'
    | '/connect'
    | '/docs'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/agent-manifest.json'
    | '/.well-known/agents.json'
    | '/.well-known/ai-plugin.json'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/keys'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/usage'
    | '/api/agent'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/'
    | '/api/public/stripe/webhook'
    | '/api/public/v1/claim'
    | '/api/public/v1/me'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/pricing'
    | '/api/public/v1/signup'
    | '/api/public/v1/tools'
    | '/api/public/v1/credits/purchase'
    | '/api/public/v1/keys/rotate'
    | '/api/public/v1/tools/$toolName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClaimRoute: typeof ClaimRoute
  ConnectRoute: typeof ConnectRoute
  DocsRoute: typeof DocsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  DotwellKnownAgentManifestDotjsonRoute: typeof DotwellKnownAgentManifestDotjsonRoute
  DotwellKnownAgentsDotjsonRoute: typeof DotwellKnownAgentsDotjsonRoute
  DotwellKnownAiPluginDotjsonRoute: typeof DotwellKnownAiPluginDotjsonRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAgentRoute: typeof ApiAgentRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicV1ClaimRoute: typeof ApiPublicV1ClaimRoute
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
  ApiPublicV1PricingRoute: typeof ApiPublicV1PricingRoute
  ApiPublicV1SignupRoute: typeof ApiPublicV1SignupRoute
  ApiPublicV1ToolsRoute: typeof ApiPublicV1ToolsRouteWithChildren
  ApiPublicV1CreditsPurchaseRoute: typeof ApiPublicV1CreditsPurchaseRoute
  ApiPublicV1KeysRotateRoute: typeof ApiPublicV1KeysRotateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-manifest.json': {
      id: '/.well-known/agent-manifest.json'
      path: '/.well-known/agent-manifest.json'
      fullPath: '/.well-known/agent-manifest.json'
      preLoaderRoute: typeof DotwellKnownAgentManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agents.json': {
      id: '/.well-known/agents.json'
      path: '/.well-known/agents.json'
      fullPath: '/.well-known/agents.json'
      preLoaderRoute: typeof DotwellKnownAgentsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-plugin.json': {
      id: '/.well-known/ai-plugin.json'
      path: '/.well-known/ai-plugin.json'
      fullPath: '/.well-known/ai-plugin.json'
      preLoaderRoute: typeof DotwellKnownAiPluginDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/claim': {
      id: '/api/public/v1/claim'
      path: '/api/public/v1/claim'
      fullPath: '/api/public/v1/claim'
      preLoaderRoute: typeof ApiPublicV1ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/pricing': {
      id: '/api/public/v1/pricing'
      path: '/api/public/v1/pricing'
      fullPath: '/api/public/v1/pricing'
      preLoaderRoute: typeof ApiPublicV1PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/signup': {
      id: '/api/public/v1/signup'
      path: '/api/public/v1/signup'
      fullPath: '/api/public/v1/signup'
      preLoaderRoute: typeof ApiPublicV1SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tools': {
      id: '/api/public/v1/tools'
      path: '/api/public/v1/tools'
      fullPath: '/api/public/v1/tools'
      preLoaderRoute: typeof ApiPublicV1ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/credits/purchase': {
      id: '/api/public/v1/credits/purchase'
      path: '/api/public/v1/credits/purchase'
      fullPath: '/api/public/v1/credits/purchase'
      preLoaderRoute: typeof ApiPublicV1CreditsPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/rotate': {
      id: '/api/public/v1/keys/rotate'
      path: '/api/public/v1/keys/rotate'
      fullPath: '/api/public/v1/keys/rotate'
      preLoaderRoute: typeof ApiPublicV1KeysRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tools/$toolName': {
      id: '/api/public/v1/tools/$toolName'
      path: '/$toolName'
      fullPath: '/api/public/v1/tools/$toolName'
      preLoaderRoute: typeof ApiPublicV1ToolsToolNameRouteImport
      parentRoute: typeof ApiPublicV1ToolsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1ToolsRouteChildren {
  ApiPublicV1ToolsToolNameRoute: typeof ApiPublicV1ToolsToolNameRoute
}

const ApiPublicV1ToolsRouteChildren: ApiPublicV1ToolsRouteChildren = {
  ApiPublicV1ToolsToolNameRoute: ApiPublicV1ToolsToolNameRoute,
}

const ApiPublicV1ToolsRouteWithChildren =
  ApiPublicV1ToolsRoute._addFileChildren(ApiPublicV1ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClaimRoute: ClaimRoute,
  ConnectRoute: ConnectRoute,
  DocsRoute: DocsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  DotwellKnownAgentManifestDotjsonRoute: DotwellKnownAgentManifestDotjsonRoute,
  DotwellKnownAgentsDotjsonRoute: DotwellKnownAgentsDotjsonRoute,
  DotwellKnownAiPluginDotjsonRoute: DotwellKnownAiPluginDotjsonRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAgentRoute: ApiAgentRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicV1ClaimRoute: ApiPublicV1ClaimRoute,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
  ApiPublicV1PricingRoute: ApiPublicV1PricingRoute,
  ApiPublicV1SignupRoute: ApiPublicV1SignupRoute,
  ApiPublicV1ToolsRoute: ApiPublicV1ToolsRouteWithChildren,
  ApiPublicV1CreditsPurchaseRoute: ApiPublicV1CreditsPurchaseRoute,
  ApiPublicV1KeysRotateRoute: ApiPublicV1KeysRotateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
